version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map client port to host

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5100:5100" # Map server port to host

